    # Etapa 1: Build da aplicação React
    FROM node:20-alpine AS build

    WORKDIR /usr/src/app

    COPY package*.json ./
    RUN npm install --legacy-peer-deps

    COPY . .
    RUN npm run build

    # Etapa 2: Servir os arquivos estáticos com Nginx
    FROM nginx:alpine

    # Copia os arquivos compilados do React para o Nginx
    COPY --from=build /usr/src/app/dist /usr/share/nginx/html

    # COPIA O SEU ARQUIVO DE CONFIGURAÇÃO LOCAL PARA DENTRO DO CONTAINER
    COPY nginx.conf /etc/nginx/conf.d/default.conf

    EXPOSE 80

    CMD ["nginx", "-g", "daemon off;"]